# Generated by Django 2.2.5 on 2019-10-24 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('stacktrace', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_msg', models.TextField()),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.PositiveIntegerField(choices=[(0, 'Unkown'), (1, 'Retry'), (2, 'Content'), (3, 'Automation')], default=0)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('situation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Situation')),
            ],
        ),
    ]
