# Generated by Django 2.2.5 on 2019-10-17 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191011_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='errorinstance',
            name='stacktrace',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.PositiveIntegerField(choices=[(0, 'Unkown'), (1, 'Retry'), (2, 'Content'), (3, 'Automation')], default=0)),
                ('text', models.TextField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Situation')),
            ],
        ),
    ]
