# Generated by Django 2.2.5 on 2019-10-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191017_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='error_message',
            new_name='error_msg',
        ),
    ]
