# Generated by Django 2.2.5 on 2019-10-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191018_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Situation'),
        ),
    ]
